### ISSUE TITLE
Add support for changing Admin URL and Port

### ISSUE THREAD

**Issue by julianxhokaxhiu** [Zimbra-Community/zimbra-docker#15]
Hi,

I really like your Dockerfile and I'm looking forward to start using it. Although I require if possible to change the Admin URL and Port since I don't want to expose the default 7071 port.

To do so, I found [this answer on ServerFault](http://serverfault.com/a/643003) which points on declaring simply two variables: `zimbraAdminPort` and `zimbraAdminURL` to be configurable.

Would be supernice if you can include them to be configured through Docker Run environment variables!

Do you think it's possible? Thanks in advance :)

**Comment by quantumtechnology** [comment]
Dear Julian,
attached is the description how I set up the docker.
You can easily change the admin url because you just need to forward a
different url to the outer machine.
I will make a docker run file when I have more time, we just got a
Science accepted on our single atom heat engine so there is a lot of
media coverage. but up to then I just send you the description here:

sudo docker run -h mysite.com -it -p 25:25 -p 81:80 -p 465:465 -p
587:587 -p 110:110 -p 143:143 -p 993:993 -p 995:995 -p 443:443 -p
8080:8080 -p 8443:8443 -p 7071:7071 -p 9071:9071 ubuntu:14.04
#you might need to rename some ports such as:
k@adventure-01:~$ sudo docker run -h mysite.com -it -p 25:25 -p 81:80 -p
465:465 -p 587:587 -p 110:110 -p 143:143 -p 993:993 -p 995:995 -p
443:443 -p 8081:8080 -p 8443:8443 -p 7071:7071 -p 9071:9071 ubuntu:14.04


#inside docker
#we have to first set /etc/resolf.conf to (this is normally done
automatically)
nameserver 134.93.8.159
nameserver 134.93.8.13
###############################

apt-get update
apt-get install libgmp10 libperl5.18 unzip pax sysstat sqlite3 dnsmasq
wget libaio1 vim dnsutils ssh

#get outer dns with
nslookup google.de

vim /etc/dnsmasq.conf
#we add external dns server inside docker:
#mx-host=mysite.local(domain), mail.mysite.local(mail), 5 
#in our case domain is equal to main server
user=root
server=134.93.8.159
server=134.93.8.13
domain=mysite.com
mx-host=mysite.com,mysite.com, 5
listen-address=127.0.0.1
#####################


vim /etc/resolv.conf
#:
# Generated by NetworkManager
search localdomain
nameserver 127.0.0.1
#####################################


service dnsmasq restart
nslookup mysite.com # should give local ip

wget
https://files.zimbra.com/downloads/8.6.0_GA/zcs-8.6.0_GA_1153.UBUNTU14_64.20141215151116.tgz
tar -xvf zcs-8.6.0_GA_1153.UBUNTU14_64.20141215151116.tgz
cd zcs*

./install.sh
do N at zimbra-dsncache

set admin pw
#use keys: 6 4 PASSWORD r a y

#
#you can do ctrl p q to do docker in background
#and then
#docker exec -it DOCKERID bash#to perform some jobs parallel to installation

You also need to edit /etc/ssh/sshd_config, and comment out the
following line:

PermitRootLogin without-password

Just below it, add the following line:

PermitRootLogin yes

Then restart SSH #a non running ssh is the major source of nonfunctionality

sudo service ssh restart

su – zimbra

zmsshkeygen
zmupdateauthkeys
#If you have a multi-server environment, run this command on the other
servers:
zmupdateauthkeys

zmcontrol restart

_____
now you can go to
https://mysite.com:7071  for admin
you should be able to view the current cerificate
make a new test account
and
https://mysite.com:444  for access
you should be able to send emails from admin to test
if not check that you do inside docker
service ssh restart
and
vim /etc/resolv.conf
#:
# Generated by NetworkManager
search localdomain
nameserver 127.0.0.1
#####################
service dnsmasq restart
___
make some space
rm -rf zcs-8.6.0_GA_1153.UBUNTU14_64.20141215151116
rm zcs-8.6.0_GA_1153.UBUNTU14_64.20141215151116.tgz

____
get certificates valid
=========================
>>>>>>>>>>>
#hint you can use
docker f5 foo.txt mycontainer:/foo.txt
docker cp mycontainer:/foo.txt foo.txt
#alternatively use scp:
passwd
#now you can
scp opt/certs.tgz root@172.17.0.2:/opt/
<<<<<<<<<<

on main host do:>>>>>>>>>>>>>>>>>>

get ssl cert for main host (non docker running apache)
git clone https://github.com/letsencrypt/letsencrypt
$ cd letsencrypt
$ ./letsencrypt-auto --help

$ ./letsencrypt-auto --apache
______________________

for www.mysite.com and mysite.com
first change a and mx records to point to ip and "www.mysite."

This installs https keys
do on non docker host:

./letsencrypt-auto certonly
select apache
use as domain names:mysite.com www.mysite.com
we use 000-default-1e-ssl.conf twice as virtual host file because apache
is not configured as vhost for mysite
follow :Installing a LetsEncrypt SSL Certificate - Zimbra   Tech Center
and add the idemtrustroot certiface to chain as decribed inside the html
file
files are in:

/etc/letsencrypt/archive/mysite.com
____________

#do not letsencrypt certonly --webroot -w /var/www/example -d
example.com -d www.example.com -w /var/www/thing -d thing.is -d m.thing.is
<<<<<<<<<<<<<<<<<<<<<<<<<<<

on docker do

#install letsencrypt keys
we make
#go back with
sudo docker attach YOURCONTAINERID

#and unzip

#there check certs with:
/opt/zimbra/bin/zmcertmgr verifycrt comm privkey1.pem cert1.pem chain1.pem
#backup ssl dir
cp -a /opt/zimbra/ssl/zimbra /opt/zimbra/ssl/zimbra.$(date "+%Y%m%d")
#copy key
cp privkey1.pem /opt/zimbra/ssl/zimbra/commercial/commercial.key
#deploy
 /opt/zimbra/bin/zmcertmgr deploycrt comm cert1.pem chain1.pem
#restart
su - zimbra
zmcontrol restart

______________________________________


#now we commit the current docker container to an image:
sudo docker commit YOURCONTAINERID zimbra_fresh




#if you messed something up you can return with
sudo docker run -h mail.mysite.local -it -p 26:25 -p 81:80 -p 465:465 -p
587:587 -p 110:110 -p 143:143 -p 993:993 -p 995:995 -p 443:443 -p
8080:8080 -p 8443:8443 -p 7071:7071 -p 9071:9071 zimbra_fresh

#go back to docker with (1);



then go to
https://www.mysite.com:7071/
use admin and pw XXXXX
the certificate should be valid!

https://www.mysite.com:444/

______________________
CALDAV
https://mysite.com:444/dav/admin/Calendar
https://mysite.com:444/dav/admin/Tasks
___________
to add port forwardings, I always follow these steps,

stop running container

docker stop test01
commit the container

docker commit test01 test02
re-run from the commited image

docker run -p 8080:8080 -td test02
Where the first 8080 is the local port and the second 8080 is the
container port.
_______________________

Docker backup without commit
use export for docker container and save for images
sudo docker export 0f403a54be77 | gzip -9
>zimbra_docker_container_works.tar.gz

cat zimbra_docker_container_works.tar.gz | gzip -d -9 | docker load



#docker save <image> | bzip2 | \
#     ssh user@host 'bunzip2 | docker load'
#
#It's also a good idea to put pv in the middle of the pipe to see how
the transfer is going:
#
#docker save <image> | bzip2 | pv | \
#     ssh user@host 'bunzip2 | docker load'
!!!!!!!!!!!!!!!!!!!!!!
always after exit of docker we need to:

sudo docker start ID
sudo docker attach ID
vim /etc/resolf.conf
###
search localdomain
nameserver 127.0.0.1
###
service ssh start
service dnsmasq start

su - zimbra
zmcontrol start

**Comment by julianxhokaxhiu** [comment]
Does this method involves SSH'ing into the Zimbra docker and playing with the configuration? Would be nice to have it out of the box so it could be replicated easily...

Thanks in advance :)

**Comment by quantumtechnology** [comment]
you need to forward port 22 to another port outside to ssh directly into
the zimbra docker.
But I would just do an ssh into outer machine and a
$sudo docker attach id.
where you get id with
$docker ps -a

**Comment by julianxhokaxhiu** [comment]
My goal is to not use SSH at all inside the container. Just to "configure" it within `docker run` and the official Zimbra administrator panel regarding my data ( which will be anyway mapped with `-v` )
