### ISSUE TITLE
New ZCS 8.7.2 instructions from scratch + bug fixes in current branch

### ISSUE THREAD

**Issue by UralZima** [Zimbra-Community/zimbra-docker#27]
Hi. I wanted to do a new ZCS installation in docker. Also your branch have some bugs.

Install a new ubuntu:16.04:
# mkdir /root/zimbra # volume for zimbra
# docker run -it --name zimbra ubuntu:16.04 -v /root/zimbra:/opt/zimbra

# apt-get update && apt-get dist-upgrade
# apt-get install lsb-release sysstat resolvconf syslog-ng dnsmasq
syslog-ng required for zimbra-logger to work. Also that's why all services marked down in admin console if not installed
syslog-ng will fail to start, coz it needs /proc/kmsg, so:
# sed -i 's/internal();//g' /etc/syslog-ng/syslog-ng.conf
resolvconf will fail to install, so do (from here: https://github.com/docker/docker/issues/1297):
# echo "resolvconf resolvconf/linkify-resolvconf boolean false" | debconf-set-selections
# dpkg --configure -a
new zcs depends from resolvconf, without it it won't install

# wget https://files.zimbra.com/downloads/8.7.2_GA/zcs-8.7.2_GA_1736.UBUNTU16_64.20170131053933.tgz
# tar xzf https://files.zimbra.com/downloads/8.7.2_GA/zcs-8.7.2_GA_1736.UBUNTU16_64.20170131053933.tgz
# cd zcs*
# ./install.sh

I wanted to do a minimal install, so I didn't installed following services:
zimbra-apache, zimbra-spell, zimbra-proxy, zimbra-memcached, zimbra-dnscache
ZCS working fine without it. 
On setup, disable using proxy for mail and web, and reconfigure ports. Also I suggest disabling non-ssl imap and non-ssl pop3 ports, that's previous century. 

After install, exit container and stop it:
docker # exit
# docker stop zimbra
# docker commit zimbra zimbra-image
# docker rm zimbra

Create a new file start.sh on host
# vim /root/zimbra/start.sh
--------------
#!/bin/bash
service syslog-ng start
su zimbra -c '/opt/zimbra/bin/zmcontrol restart' > /tmp/zmlog
while true; do sleep 10000; done
--------------
I know it may be not so nice, suggest new start.sh in comments.

# docker run --restart=unless-stopped --entrypoint="/opt/zimbra/start.sh" --dns 127.0.0.1 --name zimbra -v /root/zimbra:/opt/zimbra -d zimbra-image

Now all must be fine, zimbra is running, check the /tmp/zmlog
# tail -f /tmp/zmlog

Good luck!

**Comment by UralZima** [comment]
Sorry about commands appear big, I just added # in front of it to show it's shell, markdown considered it as header

**Comment by UralZima** [comment]
Yes and don't forget about ports in last 'docker run' command, required are 25, 465,587, 993, 995, 7071

**Comment by UralZima** [comment]
But anyway Zimbra SUCKS. It can't work properly never. Even on fresh install on a fresh server.
It may say service failed, but it started, it may not start some services, but manual starting is ok. I am tired of it. I switched to iRedMail and now I am happy. 
I wish others do the same and forget about this big shit, that just can't do it's job, and never did. 
I was zimbra user since 7 versions, and it always worked bad, especially on reboots. Service status on web page NEVER showed true info. That's not normal.

**Comment by jorgedlcruz** [comment]
UralZima, a Zimbra server it has a lot of projects inside like openldap, mariadb, postfix, nginx, jetty, etc, it also requires the proper resources and DNS configuration.

Docker is not tested for Zimbra and it can have some errors, if you are using Zimbra 8.7.x and U16.04 it should work as expected, if it's not, it's better to report a bugzilla with your logs rather than write an unfortunate comment here which doesn't help anyone and doesn't reflect the reality.

About the web service status vs. the status on the CLI, it was discussed long, it's usually a rsyslog wrong configuration - https://www.jorgedelacruz.es/2014/01/21/zimbra-solucionando-error-services-not-running-cruces-rojas/

The only good thing from your comment is that now you are happy, and I'm happy for that too.
